version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:18.0
        auth:
          username: aidarionov
          password: $DOCKERHUB_PASSWORD # context / project UI env-var reference
    steps:
      - checkout
      - run:
          name: Running the Node Container
          command: |
            yarn install
      - run:
          name: Linting
          command: |
            yarn lint
            yarn typescript
