version: 2.1
jobs:
  Using-Node:
    docker:
      - image: cimg/node:17.2
        auth:
          username: aidarionov
          password: $DOCKERHUB_PASSWORD # context / project UI env-var reference
    steps:
      - run:
          name: Running the Node Container
          command: |
            yarn install
